# Generated by Django 4.1.3 on 2023-09-24 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('in', 'income'), ('re', 'rent'), ('bi', 'bill'), ('food', 'food'), ('dri', 'drink'), ('ca', 'cake')], max_length=5)),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
