# Generated by Django 4.1.3 on 2023-09-24 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodStuffs', models.CharField(max_length=40)),
                ('quantity', models.FloatField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ch', 'checked'), ('no', 'notChecked')], max_length=3)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('factorImage', models.ImageField(blank=True, null=True, upload_to='', verbose_name='home/factor/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
